### PR TITLE
fixed serialization issue (multiple backslash)

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixed a serialization issue for fields that contain multiple backslash characters

### CODE REVIEW

**Comment by phpnode** [comment]
@luigidellaquila thanks, but this bug has recurred a few times, mind adding a test for it?

**Comment by luigidellaquila** [comment]
Hi @phpnode 

no problem, I'm doing this right now.
Is the bug already tracked?  Should I file a new issue for my specific test case?

Thanks

**Comment by phpnode** [comment]
@luigidellaquila can't find any issues for it, but there's no need to create a new one, I just remember seeing this a few times before, e.g. at one point OrientDB would accept strings like `http://foo.com/` correctly but not `//foo.com/`

**Comment by luigidellaquila** [comment]
@phpnode too late ;-)
I just created an issue for this and provided a test case.
Anyway, the problem is with backslash at the end of a string, not with a slash.
eg.

```
insert into V set foo = "asdfasdf\\\\", bar = "&gt;"
```


Thanks a lot!

Luigi

**Comment by phpnode** [comment]
@luigidellaquila thanks!

**Pull request merged**
