### PR TITLE
[WIP] 2.0

### PR DESCRIPTION
**Pull request by phpnode**
This is the work in progress version 2.0 of oriento, it is written using [6to5](/6to5/6to5)

### Goals

1. Full Binary / REST support
2. Support node.js and the browser, eventually also in-database.
3. Provide a simpler, more consistent API
4. Remove unwanted functionality and footguns.
5. Clean code using ES6 constructs
6. Support all OrientDB *features*
7. Solid documentation

### Non-Goals

1. Backwards compatibility with Oriento
2. Backwards compatibility with OrientDB earlier than 2.0
3. Compatibility with very old browsers (no IE8 support, sorry)
4. Support all OrientDB *commands* (some are potentially dangerous e.g. using RECORD_UPDATE on an edge)

### Todo

- [ ] Provide a minimal but consistent "transport" layer for REST + binary protocols.
- [ ] Support all OrientDB data types (LinkSet, EmbeddedSet etc)
- [ ] Add a higher level API for interacting with the database /server
- [ ] Add a comprehensive query builder
- [ ] Port existing tests from current `master`
- [ ] Add browser builds
- [ ] Support distributed more (push data)

### CODE REVIEW

**Comment by mccarvell** [comment]
Sounds great! Looking forward to helping out with documentation.

**Comment by tychotatitscheff** [comment]
Hey, Have you an estimation of the priority and the ETA for this. Having React in ES6, koajs and co is making me envious for doing the same with the DB driver.
I would like to help if I can.

**Comment by phpnode** [comment]
@tychotatitscheff I would like to finish this too, but right now no one is sponsoring Oriento development so it is at the bottom of a long to do list

**Comment by tychotatitscheff** [comment]
@phpnode say me if  it is possible to bake this. I would probably do some small donation (30 -50 €). Or I can help with code as soon as the design is more advanced.

**Comment by phpnode** [comment]
@tychotatitscheff really appreciate the kind offer but there is at least 3 weeks fulltime work here to reach feature parity with the current release. Really this needs corporate sponsorship

**Comment by tychotatitscheff** [comment]
> phpnode deleted the 2.0 branch 12 hours ago

Saddest day ever :)

**Comment by phpnode** [comment]
@tychotatitscheff the ideas from this project are coming back in a different form, stay tuned :)

**Comment by dmarcelino** [comment]
There is hope! :)

**Comment by tychotatitscheff** [comment]
> @tychotatitscheff the ideas from this project are coming back in a different form, stay tuned :)

Best day ever :)

**Pull request closed without merging**
